import "./globals.css"
import HeaderResponsive from "../components/Mantine/Header"
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

const links = [
  { label: "Home", link: "/" },
  { label: "Boncuk", link: "/boncuk" }
]

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body>
        <HeaderResponsive links={links} />
        <main className='min-h-screen bg-background flex flex-col items-center'>{children}</main>
      </body>
    </html>
  )
}
